import { getCurrentUser } from "./getCurrentUser";
import { redirect } from "next/navigation";

export async function approvedCourses() {
  const currentUser = await getCurrentUser();
  if (!currentUser) {
    redirect("/");
  }

  try {
    const courses = [
      {
        id: 1,
        userId: 1,
        category: "Web Development",
        title: "Complete JavaScript Course 2024",
        slug: "complete-javascript-course-2024",
        description:
          "<p><em>Well-made course. Super in-depth, with great challenges and projects that will solidify your Javascript understanding. I found the lectures were paced perfectly -- Jonas doesn't skip over anything that might be useful to a JS developer\"</em>&nbsp;— Carson Bartholomew</p><p>JavaScript is the most popular programming language in the world. It powers the entire modern web. It provides millions of high-paying jobs all over the world.</p><p>That's why you want to learn JavaScript too. And you came to the right place!</p>",
        regular_price: 99,
        before_price: 149,
        lessons: "21",
        duration: "68h 34m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707203985/mwg8hiewqc1cfl7k3dvt.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>No coding experience is necessary to take this course! I take you from beginner to expert!</li><li>Any computer and OS will work — Windows, macOS or Linux. We will set up your text editor the course.</li><li>A basic understanding of HTML and CSS is a plus, but not a must! The course includes an HTML and CSS crash course.</li></ul>",
        what_you_will_learn:
          "<ul><li>Become an advanced, confident, and modern JavaScript developer from scratch</li><li>Build 6 beautiful real-world projects for your portfolio (not boring toy apps)</li><li>Become job-ready by understanding how JavaScript really works behind the scenes</li><li>How to think and work like a developer: problem-solving, researching, workflows</li></ul><p><br></p>",
        who_is_this_course_for:
          "<ul><li>Take this course if you want to gain a true and deep understanding of JavaScript</li><li>Take this course if you have been trying to learn JavaScript but: 1) still don't really understand JavaScript, or 2) still don't feel confident to code real apps</li><li>Take this course if you're interested in using a library/framework like React, Angular, Vue or Node in the future</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-06T07:21:35.780Z",
        created_at: "2024-02-06T07:21:35.780Z",
        updated_at: "2024-02-06T07:26:49.757Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 1,
            courseId: 1,
            type: "video",
            title: "Introduction",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707204118/ysmbjh5xxrddowskbrb4.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-06T07:22:03.383Z",
            updated_at: "2024-02-06T07:22:03.383Z",
          },
          {
            id: 3,
            courseId: 1,
            type: "video",
            title: "Get Image",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707204363/ljg3ntdjjguqxiku2xpe.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-06T07:22:03.383Z",
            updated_at: "2024-02-06T07:22:03.383Z",
          },
        ],
      },
      {
        id: 2,
        userId: 1,
        category: "App Development",
        title: "The Complete Flutter Development Course",
        slug: "dart-flutter-the-complete-flutter-development-course",
        description:
          "<p>Welcome to&nbsp;<strong>The Complete Flutter 2.0 Development Course</strong>. The most&nbsp;<strong>up-to-date</strong>&nbsp;Flutter course available online. Covering all the fundamental concepts for Flutter development, using the latest Flutter 2.0 version.</p><p>I’ve built this course over months, perfecting the curriculum to ensure that you come out of this course as a fully-fledged&nbsp;<strong>Flutter developer. I’ll take you from scratch</strong>&nbsp;and make you into a&nbsp;<strong>skilled Flutter developer</strong>&nbsp;with a&nbsp;<strong>strong portfolio</strong>&nbsp;of beautiful Flutter apps.</p><p>This course will teach Flutter &amp; Dart from scratch,&nbsp;<strong>NO prior knowledge</strong>&nbsp;of either of the two is required! And you certainly don't need any Android or iOS development experience since the whole idea behind Flutter is to only learn one language.</p>",
        regular_price: 149,
        before_price: 199,
        lessons: "20",
        duration: "3h 25m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707204269/pmyhthvg0xixlirzpmbk.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>A Passion To Learn</li><li>A Computer That Has Admin Privileges</li><li>10GB Of Free Space On Hard Drive.</li><li>Mac Computer RequiredAlthough you can build iOS apps on a Windows computer with Flutter, if you want to test it, you will need a Mac.</li></ul>",
        what_you_will_learn:
          "<ul><li>Become A Fully-Fledged Flutter Developer</li><li>Build Engaging Native Mobile Apps For Both Android and iOS Using Single Codebase</li><li>Build A Portfolio Of Beautiful Flutter Apps</li></ul>",
        who_is_this_course_for:
          "<ul><li>Developers Looking To Build Quality Apps With Flutter</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-06T07:25:23.890Z",
        created_at: "2024-02-06T07:25:23.890Z",
        updated_at: "2024-02-12T05:51:34.331Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 2,
            courseId: 2,
            type: "video",
            title: "Intro",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707204363/ljg3ntdjjguqxiku2xpe.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-06T07:26:11.414Z",
            updated_at: "2024-02-06T07:26:11.414Z",
          },
        ],
      },
      {
        id: 3,
        userId: 1,
        category: "Mobile Development",
        title: "Build an E-commerce and Admin App",
        slug: "build-an-e-commerce-and-admin-app",
        description:
          "<p><strong>Course Description: Flutter &amp; Firebase Mastery</strong></p><p>Learn to design, build, and debug fully functional shopping applications with Flutter and Firebase. This course offers in-depth knowledge of Flutter mobile development, Dart programming, and Firebase integration. By the end of the course, you will be equipped to manage freelance projects confidently and be well-prepared to take on a Flutter development position within a company.</p>",
        regular_price: 99,
        before_price: 199,
        lessons: "20",
        duration: "28h 7m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707716814/ahooraqaikeoou3tqp7a.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>Basic knowledge of programming</li><li>Basic understanding of Flutter</li><li>Experience with Windows or Mac application development</li><li>Access to a computer with an Internet connection</li><li>Enthusiasm for learning and applying cutting-edge algorithms to practical cases</li></ul>",
        what_you_will_learn:
          "<ul><li>Dart Programming Language - Fundamentals to expert topics</li><li>Understanding Flutter Mobile Development by building apps incrementally</li><li>Designing, building, and debugging Flutter apps</li><li>Building robust apps with Flutter</li></ul>",
        who_is_this_course_for:
          "<ul><li>Flutter and Dart learning cravers</li><li>To all people who are interested in Flutter</li><li>For people who want to make a complete app in Flutter</li><li>Companies Or Students who wants to build a ready app for production</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T05:47:45.728Z",
        created_at: "2024-02-12T05:47:45.728Z",
        updated_at: "2024-02-12T05:50:54.651Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 4,
            courseId: 3,
            type: "video",
            title: "How to install",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707716909/wf1onjz4sueikdajzjqp.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:48:34.982Z",
            updated_at: "2024-02-12T05:48:34.982Z",
          },
          {
            id: 5,
            courseId: 3,
            type: "video",
            title: "Course assets",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707716937/rasvyayznzdwvbkofouf.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:49:03.010Z",
            updated_at: "2024-02-12T05:49:03.010Z",
          },
          {
            id: 6,
            courseId: 3,
            type: "video",
            title: "Admin API management",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707716970/ay1ofotnqf7wglgthbey.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:49:34.158Z",
            updated_at: "2024-02-12T05:49:34.158Z",
          },
        ],
      },
      {
        id: 4,
        userId: 1,
        category: "Finance & Accounting",
        title: "Introduction to Finance and Accounting",
        slug: "introduction-to-finance-and-accounting",
        description:
          "<p>By the end of this course, you will also know how to value companies using several different valuation methodologies that I have used during my Wall Street career so you can come up with target prices for the companies that you are analyzing.</p><p>By the end of this course, you will also know how to analyze financial statements using many different financial ratios/formulas that I have used in my hedge fund, Goldman Sachs &amp;&nbsp;venture capital career.</p>",
        regular_price: 199,
        before_price: 249,
        lessons: "15",
        duration: "3h 25m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707717191/vwbqavr8tyzitktghuuo.jpg",
        access_time: "Lifetime",
        requirements:
          "<p>You don’t need to have any accounting or finance experience as we will cover all of the concepts from scratch. A requirement is that you have access to and a very basic understanding of how to use Microsoft Excel as we will use Microsoft Excel in the course as we will be analyzing and creating a Balance Sheet, Income Statement and Cash Flow Statement. We will also learn how to create the following from scratch using Microsoft Excel: financial models so we can come up with target prices using Discounted Cash Flow, the Weighted Average Cost of Capital, Price to Earnings, Price to Revenue, etc. – again all from scratch (assuming you have no or some accounting/finance knowledge).</p>",
        what_you_will_learn:
          "<p>For additional information, including refunds and complaints, please see&nbsp;<strong>Blockchained Snipers Terms of Use</strong>, which is linked from the footer of this page.</p><p>For more information regarding administrative policies, please contact our support using the&nbsp;<strong>Help and Support</strong>&nbsp;link at the bottom of this page.</p>",
        who_is_this_course_for:
          "<ul><li>Anyone interested in how accounting works (no prior accounting experience is needed).</li><li>Anyone interested in how finance works (no prior finance experience is needed).</li><li>Anyone interested in how modeling works (no prior modeling experience is needed).</li><li>Anyone interested in how valuation works (no prior valuation experience is needed).</li><li>Anyone interested in how financial ratios works (no prior financial ratios experience is needed).</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T05:54:14.226Z",
        created_at: "2024-02-12T05:54:14.226Z",
        updated_at: "2024-02-12T05:58:10.640Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 8,
            courseId: 4,
            type: "video",
            title: "Income Statement Analysis",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 9,
            courseId: 4,
            type: "video",
            title: "Cash Flow Statement Analysis",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 10,
            courseId: 4,
            type: "video",
            title: "Balance Sheet Analysis",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
      {
        id: 5,
        userId: 1,
        category: "Business",
        title: "An Entire MBA in 1 Course - Complete",
        slug: "an-entire-mba-in-1-course",
        description:
          '<p>This course will focus on business concepts that you need to know that might not be common sense. This course makes the general business, accounting and finance process very easy to understand! The professor of this course is also the author of "<em>101 Crucial Lessons They Don\'t Teach You in Business School</em>," which Forbes magazine recently called "<em>1 of 6 books that all entrepreneurs need to read right now</em>."</p><p>The contents of this course are all based on my work experience at several firms, including Goldman Sachs, the consulting industry at Accenture, a few companies I have started, the hedge fund industry where I worked at Citadel and also in the venture capital sector (the firm I founded had a venture capital investment in Facebook).I included helpful practical business concepts I learned while I did an MBA at Columbia University and a Bachelor of Commerce degree at McGill University. Think of this course as a “greatest hits” business summaries from my MBA, undergraduate business degree, work experience in consulting, equities, hedge funds, venture capital and starting my own companies.</p><p>I have minimized “boring theoretical concepts” in this course in order to keep it as close to reality as possible. The concepts of this course have been taught by me in many classes at several universities, where the student feedback has been universally and incredibly positive (please see my LinkedIn profile for student reviews / feedback on my teaching style/effectiveness - thank you. Also please see reviews of my books in Amazon and here in Udemy on my teaching - particularly in my Udemy course on "<em>101 Crucial Lessons They Don\'t Teach You in Business School</em>").</p>',
        regular_price: 200,
        before_price: 300,
        lessons: "80",
        duration: " 28h 7m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707717581/znronmo1rj2gexfrmnmy.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>Nothing except a positive attitude! : )</li></ul>",
        what_you_will_learn:
          "<ul><li>Over 450,000 students in 195 countries!</li><li>Superb reviews!</li><li>Free 384 page book version of this course included!</li><li>Take your career to the next level!</li><li>Launch a company from scratch.</li><li>Get any job the easy way.</li><li>Get many customers by using the best networking tool!</li><li>Raise a lot of money quickly.</li><li>Create financial models from scratch (the Professor makes it so easy to understand).</li><li>Analyze company financials with ease!</li><li>Understand how investment banking firms work and what they can do to help your business.</li></ul>",
        who_is_this_course_for:
          "<ul><li>Anyone interested in learning about business (only practical concepts that you can use and no boring theory + we won't cover business topics that are common sense).</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T06:00:56.394Z",
        created_at: "2024-02-12T06:00:56.394Z",
        updated_at: "2024-02-12T06:08:57.072Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 11,
            courseId: 5,
            type: "video",
            title: "How to Start a Successful Company",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 12,
            courseId: 5,
            type: "video",
            title: "How to Legally Protect Your Company",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 13,
            courseId: 5,
            type: "video",
            title: "How to Ask me Questions",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
      {
        id: 6,
        userId: 1,
        category: "Office Productivity",
        title: "Apple Mac Basics Complete Course",
        slug: "apple-mac-basics-complete-course",
        description:
          '<p><span style="color: rgb(45, 47, 49);">The Apple Mac OS for beginners course is designed with Apple Mac OS beginners in mind. The Apple Mac OS course is designed to take you from beginner to advanced so that you will be able to get the most out of your Apple Mac. This course can use this course as an Introduction to Mac OS for anyone who is new to Apple Mac. The tutorials can be used as a refresher course to get you back up to speed on Mac OS. This Apple Mac Basics Course is also great for anyone coming from Windows and are new to Mac OS and want.</span></p>',
        regular_price: 9,
        before_price: 99,
        lessons: "20",
        duration: " 1h 28m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707717815/kuz7crwi6y9rsrlrms5k.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>Students should have an Apple Mac Computer, or have access to one.</li><li>No previous experience is required in order to complete this course.</li></ul>",
        what_you_will_learn:
          "<ul><li>Students will learn how to navigate the Apple Mac OS operating system</li><li>Will learn helpful tips and tricks to increase productivity</li><li>Students will learn how to use the main applications within the Mac operating system.</li></ul>",
        who_is_this_course_for:
          "<ul><li>Beginners to Mac OS operating system.</li><li>Have a Mac or have Access to one</li><li>Be willing to learn</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T06:04:19.017Z",
        created_at: "2024-02-12T06:04:19.017Z",
        updated_at: "2024-02-12T06:08:57.725Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 14,
            courseId: 6,
            type: "video",
            title: "Introduction",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 15,
            courseId: 6,
            type: "video",
            title: "Welcome Lecture",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 16,
            courseId: 6,
            type: "video",
            title: "The Desktop - Menu Bar",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
      {
        id: 7,
        userId: 1,
        category: "Design",
        title: "Graphic Design Masterclass - Learn GREAT Design",
        slug: "graphic-design-masterclass",
        description:
          "<p>We also learn the basics of&nbsp;<strong>Adobe Photoshop, illustrator and InDesign&nbsp;</strong>and do projects with real world applications. Every designer needs to know and master these programs and this course makes sure you know the essential tools to power through amazing projects.&nbsp;</p><p>In&nbsp;<strong>Adobe Photoshop,</strong>&nbsp;we will review photo editing and manipulation techniques like how to cut objects out, duotones, changing color on objects, the liquify tool and we will create a compelling YouTube thumbnail with our newly learned photoshop skills as well as an entire book cover design project.&nbsp;</p><p>In&nbsp;<strong>Adobe Illustrator</strong>, we will master the pen tool by hand tracing simple and complex shapes. We will explore the power of the shape builder tool and In the end of this section, we will design a<strong>&nbsp;complete logo design</strong>. There is an entirely new introduction and tools section that has been added where we work through a<strong>&nbsp;7 page vector tracing worksheet</strong>&nbsp;and in the end create a complex vector illustration using our newly learned illustrator vector tools. Lastly, we will put together an&nbsp;<strong>event flyer&nbsp;</strong>to practice our layout skills, and even work through the<strong>&nbsp;branding process and create a logo</strong>, business card and letterhead for a business.</p>",
        regular_price: 99,
        before_price: 149,
        lessons: "20",
        duration: "5h 35m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707718012/kfqgp5giv1iyjlqdoaz1.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>Access to Adobe Photoshop, Illustrator &amp; InDesign (Or Affinity Designer, Affinity Photo, Affinity Publisher as an Alternative). I will be using the Adobe Creative Cloud versions, but those with older version can still get a lot out of this class. Those wanting to take the course with Affinity products will find some tools and names do differ so Adobe is preferred.</li></ul>",
        what_you_will_learn:
          '<p><strong style="color: rgb(45, 47, 49);">Logo Design</strong></p><p><strong style="color: rgb(45, 47, 49);">Print &amp; Editorial Design</strong></p><p><strong style="color: rgb(45, 47, 49);">Pattern Design and Illustration</strong></p><p><strong style="color: rgb(45, 47, 49);">Package Design</strong></p><p><strong style="color: rgb(45, 47, 49);">Branding Design</strong></p><p><strong style="color: rgb(45, 47, 49);">UX/UI Design</strong></p><p><strong style="color: rgb(45, 47, 49);">Social Media/Digital Graphic Designer</strong></p>',
        who_is_this_course_for:
          "<ul><li>Anyone interested in creating compelling and GREAT design.</li><li>Those interested in learning Photoshop, Illustrator and InDesign (Affinity Designer Too!)</li><li>Those wanting to understand graphic design basics and theory paired with real world projects and applications</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T06:07:37.343Z",
        created_at: "2024-02-12T06:07:37.343Z",
        updated_at: "2024-02-12T06:08:58.433Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 17,
            courseId: 7,
            type: "video",
            title: "Graphic Design Facebook Group",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 18,
            courseId: 7,
            type: "video",
            title: "he Step-by-Step Process of Becoming a Graphic Designer",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 19,
            courseId: 7,
            type: "video",
            title: "The Anatomy of Typography",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 20,
            courseId: 7,
            type: "video",
            title: "Detailed Review and History of Serif Fonts",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
      {
        id: 8,
        userId: 1,
        category: "Marketing",
        title: "Complete Listing Optimization Training",
        slug: "complete-listing-optimization-training",
        description:
          "<p>Are you looking for a Google My Business (GMB) course that shows you how to rank Google My Business listings?</p><p>Great, you’re in the right place.</p><p>Maybe you own a local business and would like to optimize your GMB listing OR maybe you would like to learn the whole process so you can offer it as a service to local business owners.</p><p>Whichever one it is, you can be sure I’ve got you covered.</p><p>I don’t just talk the talk; I walk the walk and live it too.</p><p>In this course, you’ll be able to watch me in real-time as I optimize a LIVE Google My Business listing and get it ranked.</p><p>At the end of the course, you’ll find that this GMB listing is ranking for some BIG keywords.</p><p>The process I follow throughout the course is the SAME process I use when ranking my client GMBs, so you can be confident what you’re learning is indeed used in the real world and does work.</p>",
        regular_price: 19,
        before_price: 29,
        lessons: "10",
        duration: "3h 25m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707718314/nlvyu6eejci1nuri8olx.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>No previous SEO knowledge or experience is required</li><li>You should have a Google My Business listing you can optimise (or one you plan to optimise in the future)</li></ul>",
        what_you_will_learn:
          "<ul><li>Learn how to optimize your Google My Business listing</li><li>Find out what the top GMB ranking factors are</li><li>Find out what citations are and how to build them to correct way</li><li>How to generate more reviews for your business</li><li>How to deal with fake reviews on your GMB listing</li></ul>",
        who_is_this_course_for:
          "<ul><li>Anyone interested in learning more about Google My Business optimizations</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T06:13:22.117Z",
        created_at: "2024-02-12T06:13:22.117Z",
        updated_at: "2024-02-12T06:16:11.405Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 21,
            courseId: 8,
            type: "video",
            title: "Start Here: Read Me Before You Start\r\n",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 22,
            courseId: 8,
            type: "video",
            title: "What To Expect + Proof This Works",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 23,
            courseId: 8,
            type: "video",
            title: "How To Check If You Already Have A GMB listing",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 24,
            courseId: 8,
            type: "video",
            title: "How To Set Up A GMB Listing",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 25,
            courseId: 8,
            type: "video",
            title: "How To Navigate Around The GMB Dashboard",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 26,
            courseId: 8,
            type: "video",
            title: "What We're Going To Cover In This Section",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 27,
            courseId: 8,
            type: "video",
            title: "GMB Ranking Factors",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 28,
            courseId: 8,
            type: "video",
            title: "The 9 Elements To Optimize On A GMB Listing",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 29,
            courseId: 8,
            type: "video",
            title: "How To Optimise Your GMB Listing",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 30,
            courseId: 8,
            type: "video",
            title:
              "How To Find Out What GMB Categories Your Competitors Have Selected",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 31,
            courseId: 8,
            type: "video",
            title: "How To Handle Multiple Locations For GMBs",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
      {
        id: 9,
        userId: 1,
        category: "Health & Fitness",
        title: "Spa Relaxation Massage Certificate Course",
        slug: "spa-relaxation-massage-certificate-course",
        description:
          '<p>Wouldn\'t you just love to know how to do this incredible form of massage?</p><p>Well, you can from best-selling massage course instructor, Mark Perren-Jones.</p><p>Mark\'s Massage Spa had&nbsp;the&nbsp;first&nbsp;100 out of&nbsp;100 reviews&nbsp;on Tripadvisor&nbsp;<strong>ALL 5 STAR</strong>!&nbsp;They were also shortlisted this year for the&nbsp;2017 Spa &amp; Wellness Awards for the Americas. Mark has done massage for elite athletes, celebrities, and Presidents of Countries and is going to show you the same massage sequence that he did for them.</p><p><em>"This massage&nbsp;course is worth every dime. In my opinion, the instructor and his team went above and beyond with quality lesson plans. I recommend to serious massage therapists who want to become great, take this course. You will not be disappointed."</em></p><p><em>"This is one of the best massage courses I have ever taken!"</em></p><p><em>"Excellent and expert instruction. Beautiful videos. These methods are far superior to what we were taught in aesthetic and spa training classes."</em></p><p><em>"Because I want people to know how awesome this course is! I am someone with no experience with massage, but seeing this massage&nbsp;course, I was inspired to take it up for my wife, and I have loved it!"</em></p><p><em>"I had gotten to a point where I wasn\'t sure if this was a career I wanted to continue but now I have a renewed sense of passion!"</em></p><p><em>"Two Giant Thumbs Way Up!"</em></p><p>Want to learn massage online?&nbsp;</p><p>Whether you would just like to learn massage online because you would like to treat your family, friends or partner or you are a massage therapist-You have come to the right place!</p><p>To do great massages, it is imperative to get the correct massage training.&nbsp;</p><p>When it comes to a massage clinic or spa, your best asset is your massage. Without an incredible massage sequence and techniques, it will be very difficult to have a thriving practice.</p><p>This online massage&nbsp;course will give you the skill set to give your clients or your friends or family&nbsp;an amazing relaxation massage experience.</p><p>&nbsp;It doesn\'t matter whether you have had&nbsp;massage training&nbsp;before or have no experience at all.&nbsp;</p><p>In this relaxation&nbsp;massage training course,&nbsp;Mark guides you step by step and shows you not only what his 20 years of experience has helped him, but also he shows you the ways to avoid the mistakes that he has made along the way.&nbsp;</p>',
        regular_price: 199,
        before_price: 399,
        lessons: "20",
        duration: "2h 6m total length",
        image:
          "https://res.cloudinary.com/dev-empty/image/upload/v1707718696/ndaky6dsbqz17jo9pvo9.jpg",
        access_time: "Lifetime",
        requirements:
          "<ul><li>In this best-selling massage course, you will need a thirst for knowledge and a desire to do your best</li><li>In this best-selling massage course, you will need a willingness to put in the hours to practice and hone your massage skills</li><li>In this best-selling massage course, you need to apply yourself once you have learned the massage techniques that I show you. If you do this and practice you will be on your way to having a very successful career</li><li>You will need a massage table, oils or creams, towels, and sheets, a pillow plus someone to practice on- I suggest if you don't already have these look at section 1 of the course for guidance first</li></ul><p><br></p>",
        what_you_will_learn:
          "<ul><li>You will get a Certificate of Completion when you finish this massage course from Mark personally</li><li>You will be able to perform our relaxation massage sequence, plus have a wealth of knowledge on other aspects of the spa business that has made us No. 1!</li><li>You will understand how to perform massage using correct body mechanics</li><li>You will know what you need to do to give a massage client an incredible massage experience from the moment she/he walks into your room/spa</li><li>You will know how to avoid the many mistakes and pitfalls that so many other massage therapists make</li><li>You will have the tools to build your own highly successful spa or massage clinic</li></ul>",
        who_is_this_course_for:
          "<ul><li>This massage course is for those who want a career in massage or want to improve their existing massage skills</li><li>This massage course will give those of you who want to become a professional massaeur or even just a person who wants to earn extra money the necessary skills to succeed</li></ul>",
        status: "Approved",
        in_home_page: false,
        in_home_page_set_at: "2024-02-12T06:20:01.046Z",
        created_at: "2024-02-12T06:20:01.046Z",
        updated_at: "2024-02-12T06:22:29.114Z",
        user: {
          id: 1,
          name: "John Doe",
          designation: null,
          email: "instructor@edemy.com",
          emailVerified: null,
          image: null,
          hashedPassword:
            "$2a$12$aEkqHjxHcUJIkSonDHK0B.xdFzCRPkDujmMnt8oM/15hF7tqZpZgG",
          role: "ADMIN",
          is_instructor: false,
          created_at: "2024-02-06T07:17:13.567Z",
          updated_at: "2024-02-06T07:17:13.567Z",
        },
        assets: [
          {
            id: 32,
            courseId: 9,
            type: "video",
            title:
              "You can join our Facebook group if you want. It is a great resource",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 33,
            courseId: 9,
            type: "video",
            title: "The Table-The 4 most Important things about your Table",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 34,
            courseId: 9,
            type: "video",
            title: "Creams and OIls-What's Great and what's not",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 35,
            courseId: 9,
            type: "video",
            title: "The Set-up of the table",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 36,
            courseId: 9,
            type: "video",
            title:
              "Some things that make the massage experience even more amazing.",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 37,
            courseId: 9,
            type: "video",
            title: "It's all in the Timing!\r\n",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
          {
            id: 38,
            courseId: 9,
            type: "video",
            title: "Why I Don't include these things in my massages",
            file_url: null,
            video_url:
              "https://res.cloudinary.com/dev-empty/video/upload/v1707717325/naqqf7oy5awhy2xwzy8k.mp4",
            video_length: null,
            is_preview: false,
            created_at: "2024-02-12T05:55:29.652Z",
            updated_at: "2024-02-12T05:55:29.652Z",
          },
        ],
      },
    ];
    return { courses };
  } catch (error) {
    // console.error("Error fetching counts:", error);
  }
}
